name: snakemake
channels:
- bioconda
- conda-forge
dependencies:
- biopython=1.79
- datavzrd
- flake8
- gatk4=4.4.0.0
- mamba=0.25
- pandas=1.4
- pytest=7.1
- pytest-cov=3.0
- python=3.11.4
- snakefmt=0.6
- snakemake==7.32.4

